consoleInput <- function(){
        funcDir <- 'C:/DS Capstone/DataScienceCapstone/DataScienceCapstone/'
        dataDir <- 'C:/DS Capstone/DataScienceCapstone/data/en_US/'
        
        setwd(funcDir)
        source('filterSpecial.R')
        source('countWords.R')
        source('countTwo.R')
        source('countMany.R')
        
        # Initial Read of Blog Data
        data <- readLines(paste0(dataDir, 'en_US.blogs.txt'))
        fdata <- filterSpecial(data, n = 3)
        gdata <- countWords(fdata)
        write.csv(gdata, 'Blogs Single Word Counts.csv', row.names = FALSE)
        gdata <- countTwo(fdata)
        write.csv(gdata, 'Blogs Two Word Counts.csv', row.names = FALSE)
        gdata <- countMany(fdata, n = 3)
        write.csv(gdata, 'Blogs Three Word Counts.csv', row.names = FALSE)
        gdata <- countMany(fdata, n = 4)
        write.csv(gdata, 'Blogs Four Word Counts.csv', row.names = FALSE)
        gdata <- countMany(fdata, n = 5)
        write.csv(gdata, 'Blogs Five Word Counts.csv', row.names = FALSE)
        
        # Initial Read of News Data
        data <- readLines(paste0(dataDir, 'en_US.news.txt'))
        fdata <- filterSpecial(data, n = 3)
        gdata <- countWords(fdata)
        write.csv(gdata, 'News Single Word Counts.csv', row.names = FALSE)
        gdata <- countTwo(fdata)
        write.csv(gdata, 'News Two Word Counts.csv', row.names = FALSE)
        gdata <- countMany(fdata, n = 3)
        write.csv(gdata, 'News Three Word Counts.csv', row.names = FALSE)
        gdata <- countMany(fdata, n = 4)
        write.csv(gdata, 'News Four Word Counts.csv', row.names = FALSE)
        gdata <- countMany(fdata, n = 5)
        write.csv(gdata, 'News Five Word Counts.csv', row.names = FALSE)
        
        # Initial Read of Twitter Data
        data <- readLines(paste0(dataDir, 'en_US.twitter.txt'))
        fdata <- filterSpecial(data, n = 8)
        gdata <- countWords(fdata)
        write.csv(gdata, 'Twitter Single Word Counts.csv', row.names = FALSE)
        gdata <- countTwo(fdata)
        write.csv(gdata, 'Twitter Two Word Counts.csv', row.names = FALSE)
        gdata <- countMany(fdata, n = 3)
        write.csv(gdata, 'Twitter Three Word Counts.csv', row.names = FALSE)
        gdata <- countMany(fdata, n = 4)
        write.csv(gdata, 'Twitter Four Word Counts.csv', row.names = FALSE)
        gdata <- countMany(fdata, n = 5)
        write.csv(gdata, 'Twitter Five Word Counts.csv', row.names = FALSE)
        
        source('filter.R')
        
        # Initial Cleaning of Blogs Data
        data <- read.csv('Blogs Single Word Counts.csv', colClasses = c('character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'Blogs Single Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'Blogs Two Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'Blogs Three Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'Blogs Four Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'Blogs Five Word Counts.csv', row.names = FALSE)
        
        # Initial Cleaning of News Data
        data <- read.csv('News Single Word Counts.csv', colClasses = c('character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'News Single Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'News Two Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'News Three Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'News Four Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'News Five Word Counts.csv', row.names = FALSE)
        
        # Initial Cleaning of Twitter Data
        data <- read.csv('Twitter Single Word Counts.csv', colClasses = c('character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'Twitter Single Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'Twitter Two Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, )
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'Twitter Four Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(clean, 'Twitter Five Word Counts.csv', row.names = FALSE)
        
        # (Optional) Top Three Sorting of Separate Data
        source('topThree.R')
        
        # Top Three Sorting of Twitter Data
        data <- read.csv('Twitter Single Word Counts.csv', colClasses = c('character', 'numeric'))
        merged <- topThree(data)
        write.csv(merged, 'Twitter Single Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(merged, 'Twitter Two Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(merged, 'Twitter Three Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(merged, 'Twitter Four Word Counts.csv', row.names = FALSE)
        data <- read.csv('Twitter Two Word Counts.csv', colClasses = c('character', 'character', 'numeric'))
        clean <- filter(data)
        write.csv(merged, 'Twitter Five Word Counts.csv', row.names = FALSE)
        
}